// import autoSidebar from './theme/plugins/autoSidebarBeta'

// export default {
//   '/': [
//     {
//       text: '开始阅读',
//       collapsed: false,
//       items: [
//         { text: '阅读须知', link: '/guide' },
//         { text: '学习圈子', link: '/zsxq' },
//         { text: '资源导航', link: '/favorites' },
//         { text: 'Arc 激活码获取', link: '/arc' },
//         { text: '2022 年终总结', link: '/2022' },
//         { text: '关于 ChoDocs', link: '/chodocs' },
//         { text: '参与贡献指南', link: '/contributing' },
//       ],
//     },
//     {
//       text: '📔 前端设计模式',
//       collapsed: false,
//       items: [
//         { text: '导读', link: '/patterns/guide/' },
//         { text: '单例模式', link: '/patterns/singleton-pattern/' },
//         { text: '代理模式', link: '/patterns/proxy-pattern/' },
//         { text: '提供者模式', link: '/patterns/provider-pattern/' },
//         { text: '原型模式', link: '/patterns/prototype-pattern/' },
//         { text: '容器/演示模式', link: '/patterns/container-presentational-pattern/' },
//         { text: '观察者模式', link: '/patterns/observer-pattern/' },
//         { text: '模块模式', link: '/patterns/module-pattern/' },
//         { text: '混合模式', link: '/patterns/mixin-pattern/' },
//         { text: '中介/中间件模式', link: '/patterns/middleware-pattern/' },
//       ],
//     },
//     {
//       text: '📘 TS 学习',
//       collapsed: false,
//       items: [
//         { text: '导读', link: '/ts/ch' },
//         { text: '环境配置', link: '/ts/ch0' },
//         { text: '基础操作', link: '/ts/ch1' },
//         { text: '工具类', link: '/ts/ch2' },
//         { text: '函数系统', link: '/ts/ch3' },
//         { text: '泛型', link: '/ts/ch4' },
//       ],
//     },
//     {
//       text: '📗 编程学习',
//       collapsed: false,
//       items: [
//         { text: '发布 npm 包', link: '/program/npm-package/' },
//         { text: '给 VitePress 添加 algolia 搜索', link: '/program/vitepress-algolia/' },
//         { text: '接上 algolia 搜索（补充）', link: '/program/vitepress-algolia-plus/' },
//         { text: '接上 algolia 搜索（解决）', link: '/program/vitepress-algolia-solved/' },
//         { text: '给 VitePress 添加本地搜索功能', link: '/program/vitepress-local-search/' },
//       ],
//     },
//     {
//       text: '📝 备忘录',
//       collapsed: false,
//       items: [{ text: 'Git 命令', link: '/memo/git-command/' }],
//     },
//   ],
//   '/algorithm/': [
//     {
//       items: [
//         { text: '📓 导读', link: '/algorithm/guide/' },
//       ],
//     },
//     {
//       text: 'Hash Table 哈希表',
//       collapsed: false,
//       items: [
//         { text: '介绍', link: '/algorithm/hash-table/' },
//         { text: '1. 两数之和', link: '/algorithm/hash-table/1.两数之和' },
//         { text: '3. 无重复字符的最长子串', link: '/algorithm/hash-table/3.无重复字符的最长子串' },
//         { text: '136. 只出现一次的数字', link: '/algorithm/hash-table/136.只出现一次的数字' },
//         { text: '349. 两个数组的交集', link: '/algorithm/hash-table/349.两个数组的交集' },
//         { text: '560. 和为 K 的子数组', link: '/algorithm/hash-table/560.和为 K 的子数组' },
//       ],
//     },
//     {
//       text: 'Stack 栈',
//       collapsed: false,
//       items: [
//         { text: '20. 有效的括号', link: '/algorithm/stack/20.有效的括号' },
//         { text: '739. 每日温度', link: '/algorithm/stack/739.每日温度' },
//         { text: '901. 股票价格跨度', link: '/algorithm/stack/901.股票价格跨度' },
//         { text: '907. 子数组的最小值之和', link: '/algorithm/stack/907.子数组的最小值之和' },
//         { text: '921. 使括号有效的最少添加', link: '/algorithm/stack/921.使括号有效的最少添加' },
//         { text: '946. 验证栈序列', link: '/algorithm/stack/946.验证栈序列' },
//         { text: '1190. 反转每对括号间的子串', link: '/algorithm/stack/1190.反转每对括号间的子串' },
//         { text: '1249. 移除无效的括号', link: '/algorithm/stack/1249.移除无效的括号' },
//       ],
//     },
//     {
//       text: 'Queue 队列',
//       collapsed: false,
//       items: [
//         { text: '933. 最近的请求次数', link: '/algorithm/queue/933.最近的请求次数' },
//       ],
//     },
//     {
//       text: 'Backtracking 递归与回溯',
//       collapsed: false,
//       items: [
//         { text: '08.08. 有重复字符串的排列组合', link: '/algorithm/recursion-backtracking/08.08.有重复字符串的排列组合' },
//         { text: '16.11. 跳水板', link: '/algorithm/recursion-backtracking/16.11.跳水板' },
//         { text: '17. 电话号码的字母组合', link: '/algorithm/recursion-backtracking/17.电话号码的字母组合' },
//         { text: '22. 括号生成', link: '/algorithm/recursion-backtracking/22.括号生成' },
//         { text: '37. 解数独', link: '/algorithm/recursion-backtracking/37.解数独' },
//         { text: '39. 组合总和', link: '/algorithm/recursion-backtracking/39.组合总和' },
//         { text: '40. 组合总和 II', link: '/algorithm/recursion-backtracking/40.组合总和 II' },
//         { text: '46. 全排列', link: '/algorithm/recursion-backtracking/46.全排列' },
//         { text: '47. 全排列 II', link: '/algorithm/recursion-backtracking/47.全排列 II' },
//         { text: '51. N 皇后', link: '/algorithm/recursion-backtracking/51.N 皇后' },
//         { text: '54. 螺旋矩阵', link: '/algorithm/recursion-backtracking/54.螺旋矩阵' },
//         { text: '59. 螺旋矩阵 II', link: '/algorithm/recursion-backtracking/59.螺旋矩阵 II' },
//         { text: '73. 矩阵置零', link: '/algorithm/recursion-backtracking/73.矩阵置零' },
//         { text: '77. 组合', link: '/algorithm/recursion-backtracking/77.组合' },
//         { text: '78. 子集', link: '/algorithm/recursion-backtracking/78.子集' },
//         { text: '79. 单词搜索', link: '/algorithm/recursion-backtracking/79.单词搜索' },
//         { text: '90. 子集 II', link: '/algorithm/recursion-backtracking/90.子集 II' },
//         { text: '93. 复原IP地址', link: '/algorithm/recursion-backtracking/93.复原IP地址' },
//         { text: '131. 分割回文串', link: '/algorithm/recursion-backtracking/131.分割回文串' },
//         { text: '212. 单词搜索', link: '/algorithm/recursion-backtracking/212.单词搜索' },
//         { text: '216. 组合总和 III', link: '/algorithm/recursion-backtracking/216.组合总和 III' },
//         { text: '401. 二进制手表', link: '/algorithm/recursion-backtracking/401.二进制手表' },
//         { text: '784. 字母大小写全排列', link: '/algorithm/recursion-backtracking/784.字母大小写全排列' },
//         { text: '980. 不同路径 III', link: '/algorithm/recursion-backtracking/980.不同路径 III' },
//         { text: '1219. 黄金矿工', link: '/algorithm/recursion-backtracking/1219.黄金矿工' },
//         { text: '1291. 顺次数', link: '/algorithm/recursion-backtracking/1291.顺次数' },
//       ],
//     },
//     {
//       text: 'Tree 二叉树',
//       collapsed: false,
//       items: [
//         { text: '100. 相同的树', link: '/algorithm/binary-tree/100.相同的树' },
//         { text: '101. 对称二叉树', link: '/algorithm/binary-tree/101.对称二叉树' },
//         { text: '102. 二叉树的层序遍历', link: '/algorithm/binary-tree/102.二叉树的层序遍历' },
//         { text: '104. 二叉树的最大深度', link: '/algorithm/binary-tree/104.二叉树的最大深度' },
//         { text: '108. 将有序数组转换为二叉搜索树', link: '/algorithm/binary-tree/108.将有序数组转换为二叉搜索树' },
//         { text: '110. 平衡二叉树', link: '/algorithm/binary-tree/110.平衡二叉树' },
//         { text: '111. 二叉树的最小深度', link: '/algorithm/binary-tree/111.二叉树的最小深度' },
//         { text: '112. 路径总和', link: '/algorithm/binary-tree/112.路径总和' },
//         { text: '113. 路径总和 II', link: '/algorithm/binary-tree/113.路径总和 II' },
//         { text: '124. 二叉树中的最大路径和', link: '/algorithm/binary-tree/124.二叉树中的最大路径和' },
//         { text: '129. 求根到叶子节点数字之和', link: '/algorithm/binary-tree/129.求根到叶子节点数字之和' },
//         { text: '144. 二叉树的前序遍历', link: '/algorithm/binary-tree/144.二叉树的前序遍历' },
//         { text: '199. 二叉树的右视图', link: '/algorithm/binary-tree/199.二叉树的右视图' },
//         { text: '236. 二叉树的最近公共祖先', link: '/algorithm/binary-tree/236.二叉树的最近公共祖先' },
//         { text: '257. 二叉树的所有路径', link: '/algorithm/binary-tree/257.二叉树的所有路径' },
//         { text: '404. 左叶子之和', link: '/algorithm/binary-tree/404.左叶子之和' },
//         { text: '437. 路径总和 III', link: '/algorithm/binary-tree/437.路径总和 III' },
//         { text: '450. 删除二叉搜索树中的节点', link: '/algorithm/binary-tree/450.删除二叉搜索树中的节点' },
//         { text: '501. 二叉搜索树中的众数', link: '/algorithm/binary-tree/501.二叉搜索树中的众数' },
//         { text: '543. 二叉树的直径', link: '/algorithm/binary-tree/543.二叉树的直径' },
//       ],
//     },
//     {
//       text: 'Linked List 链表',
//       collapsed: false,
//       items: [
//         { text: '2. 两数相加', link: '/algorithm/linked-list/2.两数相加' },
//         { text: '18. 删除链表的节点', link: '/algorithm/linked-list/18.删除链表的节点' },
//         { text: '19. 删除链表的倒数第N个节点', link: '/algorithm/linked-list/19.删除链表的倒数第N个节点' },
//         { text: '24. 两两交换链表中的节点', link: '/algorithm/linked-list/24.两两交换链表中的节点' },
//         { text: '92. 反转链表 II', link: '/algorithm/linked-list/92.反转链表 II' },
//         { text: '142. 环形链表 II', link: '/algorithm/linked-list/142.环形链表 II' },
//         { text: '203. 移除链表元素', link: '/algorithm/linked-list/203.移除链表元素' },
//         { text: '206. 反转链表', link: '/algorithm/linked-list/206.反转链表' },
//       ],
//     },
//     {
//       text: 'Dynamic Programming 动态规划',
//       collapsed: false,
//       items: [
//         { text: '62. 不同路径', link: '/algorithm/dp/62.不同路径' },
//         { text: '63. 不同路径 II', link: '/algorithm/dp/63.不同路径 II' },
//         { text: '70. 爬楼梯', link: '/algorithm/dp/70.爬楼梯' },
//         { text: '121. 买卖股票的最佳时机', link: '/algorithm/dp/121.买卖股票的最佳时机' },
//         { text: '122. 买卖股票的最佳时机 II', link: '/algorithm/dp/122.买卖股票的最佳时机 II' },
//         { text: '198. 打家劫舍', link: '/algorithm/dp/198.打家劫舍' },
//         { text: '213. 打家劫舍 II', link: '/algorithm/dp/213.打家劫舍 II' },
//         { text: '221. 最大正方形', link: '/algorithm/dp/221.最大正方形' },
//         { text: '322. 零钱兑换', link: '/algorithm/dp/322.零钱兑换' },
//       ],
//     },
//     {
//       text: 'Two Pointers 双指针',
//       collapsed: false,
//       items: [
//         { text: '11. 盛最多水的容器', link: '/algorithm/double-pointer/11.盛最多水的容器' },
//         { text: '15. 三数之和', link: '/algorithm/double-pointer/15.三数之和' },
//         { text: '16. 最接近的三数之和', link: '/algorithm/double-pointer/16.最接近的三数之和' },
//         { text: '42. 接雨水', link: '/algorithm/double-pointer/42.接雨水' },
//         { text: '75. 颜色分类', link: '/algorithm/double-pointer/75.颜色分类' },
//         { text: '209. 长度最小的子数组', link: '/algorithm/double-pointer/209.长度最小的子数组' },
//         { text: '344. 反转字符串', link: '/algorithm/double-pointer/344.反转字符串' },
//         { text: '763. 划分字母区间', link: '/algorithm/double-pointer/763.划分字母区间' },
//         { text: '925. 长按键入', link: '/algorithm/double-pointer/925.长按键入' },
//       ],
//     },
//   ],
//   '/green/': [
//     {
//       text: '🎈 ACM 经历',
//       collapsed: false,
//       items: [
//         { text: '阅读须知', link: '/green/ch' },
//         { text: '2019年 第二届信息科学与工程学院院赛-正式赛(赛后感想)', link: '/green/ch1' },
//         { text: '2019年 第二届信息科学与工程学院院赛-正式赛(赛后补题)', link: '/green/ch2' },
//         { text: '第四届全国中医药院校大学生程序设计竞赛（上篇）', link: '/green/ch3' },
//         { text: '第四届全国中医药院校大学生程序设计竞赛（下篇）', link: '/green/ch4' },
//       ],
//     }, {
//       text: '💭 项目经历',
//       collapsed: false,
//       items: [
//         { text: '🏆 从大一到大三，我与服务外包大赛', link: '/green/hl-contest/' },
//       ],
//     },
//   ],
//   '/tool/': [
//     {
//       text: '🎒 常用',
//       collapsed: false,
//       items: [
//         { text: 'emoji-list', link: '/tool/emoji-list' },
//         { text: 'finalcut 剪辑快捷键', link: '/tool/finalcut/' },
//         { text: '什么时候下班？', link: '/tool/off-time/' },
//         { text: '如何正常访问 GitHub？', link: '/tool/github520' },
//       ],
//     },
//   ],
//   // '/essay/': autoSidebar({ base: 'essay' }),
//   '/interview/': [
//     {
//       items: [
//         { text: '介绍', link: '/interview/' },
//       ],
//     },
//     {
//       text: '模拟面试',
//       collapsed: false,
//       items: [
//         { text: '介绍', link: '/interview/interviewer/' },
//         { text: '模拟面试 01', link: '/interview/interviewer/01' },
//         { text: '模拟面试 02', link: '/interview/interviewer/02' },
//         { text: '模拟面试 03', link: '/interview/interviewer/03' },
//       ],
//     },
//     {
//       text: '春招实习',
//       collapsed: false,
//       items: [
//         { text: '询问面试官的问题', link: '/interview/spring-internship/interviewer/' },
//         { text: '腾讯一面', link: '/interview/spring-internship/tencent-imweb/' },
//         { text: '字节一面准备', link: '/interview/spring-internship/bytedance-preparation/' },
//         { text: '字节一面', link: '/interview/spring-internship/bytedance1/' },
//         { text: '深信服-星耀实习', link: '/interview/spring-internship/sangfor/' },
//         { text: '恒生电子面试', link: '/interview/spring-internship/hundsun/' },
//         { text: '腾讯云 COS 一面', link: '/interview/spring-internship/tencent-cos/' },
//         { text: '春招知识整理', link: '/interview/spring-internship/summary/' },
//       ],
//     },
//     {
//       text: 'React',
//       collapsed: false,
//       items: [
//         { text: '模拟面试', link: '/interview/react-summary/' },
//       ],
//     },
//     {
//       text: 'Vue',
//       collapsed: false,
//       items: [
//         { text: '模拟面试', link: '/interview/vue/' },
//       ],
//     },
//     {
//       text: '前端基础：js/html/css/ts',
//       collapsed: false,
//       items: [
//         { text: 'JS 面试大全', link: '/interview/js/' },
//         { text: 'JS 自测清单（一）', link: '/interview/js/test/1.md' },
//         { text: 'JS 自测清单（二）', link: '/interview/js/test/2.md' },
//         { text: 'JS 自测清单（三）', link: '/interview/js/test/3.md' },
//         { text: 'CSS 面试', link: '/interview/js/css' },
//         { text: 'HTML 面试', link: '/interview/js/html' },
//         { text: 'TS 面试', link: '/interview/js/ts' },
//       ],
//     },
//     {
//       text: '操作系统/网络/浏览器',
//       collapsed: false,
//       items: [
//         { text: '操作系统', link: '/interview/system/' },
//         { text: '网络-TCP', link: '/interview/net/tcp/' },
//         { text: '网络-HTTP', link: '/interview/net/http/' },
//         { text: '网络-Websocket', link: '/interview/net/websocket/' },
//         { text: '网络-跨域问题', link: '/interview/net/cors/' },
//         { text: '浏览器-Session/Cookie/Token', link: '/interview/browser/cookie' },
//         { text: '浏览器-事件循环', link: '/interview/browser/principle/eventLoop' },
//         { text: '浏览器-输入URL到页面展示发生了什么', link: '/interview/browser/process/' },
//         { text: '浏览器-缓存', link: '/interview/browser/cache' },
//         { text: '浏览器-开发者工具', link: '/interview/browser/performance' },
//         { text: '浏览器-安全', link: '/interview/browser/safety/' },
//       ],
//     },
//   ],
// }

export default {
  '/': [
    {
      text: '开始阅读',
      collapsed: false,
      items: [
        { text: '阅读须知', link: '/guide/' },
        { text: '资源导航', link: '/guide/favorites' },
        { text: '关于我', link: '/guide/aboutme' },
        { text: '参与贡献指南', link: '/contributing/' },
      ],
    },
  ],
  '/basics/': [
    {
      text: '前端基础',
      link: '/basics/html/',
    },
    {
      text: 'HTML',
      link: '/basics/html/',
      collapsed: false,
      items: [
        { text: '总体概述', link: '/basics/html/01总体概述' },
        { text: '常用标签', link: '/basics/html/02常用标签' },
        { text: '高阶文本', link: '/basics/html/03高阶文本' },
        { text: '结构标签', link: '/basics/html/04结构标签' },
        { text: '表单标签', link: '/basics/html/05表单标签' },
        { text: '多媒体标签', link: '/basics/html/06多媒体标签' },
      ],
    },
    {
      text: 'CSS',
      link: '/basics/css/',
      collapsed: false,
      items: [
        { text: '总体概述', link: '/basics/css/01总体概述' },
        { text: '选择器', link: '/basics/css/02选择器' },
        { text: '字体背景', link: '/basics/css/03字体背景' },
        { text: '盒子模型', link: '/basics/css/04盒子模型' },
        { text: '定位', link: '/basics/css/05定位' },
        { text: '浮动布局', link: '/basics/css/06浮动布局' },
        { text: '小技巧', link: '/basics/css/07小技巧' },
        { text: 'flex', link: '/basics/css/08flex' },
        { text: 'CSS3', link: '/basics/css/09CSS3' },
        { text: 'CSS3 工作原理', link: '/basics/css/10CSS3工作原理' },
        { text: 'LESS', link: '/basics/css/11LESS' },
      ],
    },
    {
      text: 'JavaScript',
      link: '/basics/javascript/',
      collapsed: false,
      items: [
        { text: '基本语法', link: '/basics/javascript/01基本语法' },
        { text: '数据类型', link: '/basics/javascript/02数据类型' },
        { text: '流程控制', link: '/basics/javascript/03流程控制' },
        { text: '对象', link: '/basics/javascript/04对象' },
        { text: '函数', link: '/basics/javascript/05函数' },
        { text: '数组', link: '/basics/javascript/06数组' },
        { text: '常用类', link: '/basics/javascript/07常用类' },
        { text: 'DOM', link: '/basics/javascript/08DOM' },
        { text: 'BOM', link: '/basics/javascript/09BOM' },
        { text: 'JSON', link: '/basics/javascript/10JSON' },
        { text: '创建对象', link: '/basics/javascript/11创建对象' },
        { text: '继承', link: '/basics/javascript/12继承' },
      ],
    },
    {
      text: 'ES6+',
      link: '/basics/ES6/',
      collapsed: false,
      items: [
        { text: '变量声明', link: '/basics/ES6/01变量声明' },
        { text: '面向对象', link: '/basics/ES6/02面向对象' },
        { text: '解构赋值', link: '/basics/ES6/03解构赋值' },
        { text: '对象增强', link: '/basics/ES6/04对象增强' },
        { text: '箭头函数', link: '/basics/ES6/05箭头函数' },
        { text: '函数参数', link: '/basics/ES6/06函数参数' },
        { text: '操作数组', link: '/basics/ES6/07操作数组' },
        { text: '定义对象', link: '/basics/ES6/08定义对象' },
        { text: '代理与反射', link: '/basics/ES6/09代理与反射' },
        { text: '迭代器', link: '/basics/ES6/10迭代器' },
        { text: '生成器', link: '/basics/ES6/11生成器' },
        { text: 'Map 与 Set', link: '/basics/ES6/12Map与Set' },
        { text: 'Symbol', link: '/basics/ES6/13Symbol' },
        { text: '模块化', link: '/basics/ES6/14模块化' },
      ],
    },
    {
      text: '异步编程',
      link: '/basics/asynchronous/',
      collapsed: false,
      items: [
        { text: '同步与异步', link: '/basics/asynchronous/01同步与异步' },
        { text: 'Promise', link: '/basics/asynchronous/02Promise' },
        { text: 'Promise 源码', link: '/basics/asynchronous/03Promise源码' },
        { text: 'generator', link: '/basics/asynchronous/04generator' },
        { text: 'async', link: '/basics/asynchronous/05async' },
        { text: 'event_loop', link: '/basics/asynchronous/06event_loop' },
        { text: 'ajax', link: '/basics/asynchronous/07ajax' },
        { text: 'axios', link: '/basics/asynchronous/08axios' },
        { text: 'axios 源码', link: '/basics/asynchronous/09axios源码' },
      ],
    },
    {
      text: '计算机基础',
      link: '/basics/networks/',
    },
    {
      text: '网络协议',
      link: '/basics/networks/',
      collapsed: false,
      items: [
        { text: '网络分层', link: '/basics/networks/01网络分层' },
        { text: '基本概念', link: '/basics/networks/02基本概念' },
        { text: '性能指标', link: '/basics/networks/03性能指标' },
        { text: '网路复习', link: '/basics/networks/04网路复习' },
      ],
    },
    {
      text: '深入 HTTP',
      link: '/basics/http/',
      collapsed: false,
      items: [
        { text: '网络基础', link: '/basics/http/01网络基础' },
        { text: 'HTTP 协议', link: '/basics/http/02HTTP协议' },
        { text: 'HTTP 报文', link: '/basics/http/03HTTP报文' },
        { text: '状态码', link: '/basics/http/04状态码' },
        { text: 'web 服务器', link: '/basics/http/05web服务器' },
      ],
    },
    {
      text: '浏览器原理',
      link: '/basics/browser/',
      collapsed: false,
      items: [
        { text: 'Chrome 架构', link: '/basics/browser/01Chrome架构' },
        { text: '从 URL 到页面呈现', link: '/basics/browser/02从url到页面呈现' },
        { text: '渲染原理', link: '/basics/browser/03渲染原理' },
        { text: '浏览器存储', link: '/basics/browser/04浏览器存储' },
        { text: 'js 执行机制', link: '/basics/browser/05js执行机制' },
        { text: '页面循环系统', link: '/basics/browser/06页面循环系统' },
        { text: '页面相关', link: '/basics/browser/07页面相关' },
        { text: '浏览器网络', link: '/basics/browser/08浏览器网络' },
        { text: '浏览器安全', link: '/basics/browser/09浏览器安全' },
      ],
    },
    {
      text: 'V8 原理',
      link: '/basics/v8/',
      collapsed: false,
      items: [
        { text: '栈空间与堆空间', link: '/basics/v8/01栈空间与堆空间' },
        { text: '垃圾回收', link: '/basics/v8/02垃圾回收' },
        { text: '编译器与解释器', link: '/basics/v8/03编译器与解释器' },
      ],
    },
  ],
  '/advance/': [
    {
      text: 'TypeScript',
      link: '/advance/typescript/',
      collapsed: false,
      items: [
        { text: '总体概述', link: '/advance/typescript/basics/01概述' },
        { text: '类型声明', link: '/advance/typescript/basics/02类型声明' },
        { text: '枚举类型', link: '/advance/typescript/basics/03枚举类型' },
        { text: '配置选项', link: '/advance/typescript/basics/04配置选项' },
        { text: 'webpack 配置', link: '/advance/typescript/basics/05webpack配置' },
        { text: '面向对象', link: '/advance/typescript/basics/06面向对象' },
        { text: '接口', link: '/advance/typescript/basics/07接口' },
        { text: '泛型', link: '/advance/typescript/basics/08泛型' },
        { text: '类型检查机制', link: '/advance/typescript/basics/09类型检查机制' },
        { text: '高级类型', link: '/advance/typescript/basics/10高级类型' },
      ],
    },
    {
      text: 'Vue',
      collapsed: false,
      items: [
        {
          text: '2.x 基础知识',
          collapsed: false,
          items: [],
        },
        {
          text: '2.x 进阶知识',
          collapsed: false,
          items: [],
        },
        {
          text: '3.x 基础知识',
          collapsed: false,
          items: [],
        },
        {
          text: '实现原理',
          collapsed: false,
          items: [],
        },
      ],
    },
    {
      text: 'React',
      collapsed: false,
      items: [
        {
          text: '基础知识',
          collapsed: false,
          items: [
            { text: '入门概述', link: '/advance/React/React_basics/01入门概述' },
            { text: '面向组件', link: '/advance/React/React_basics/02面向组件' },
            { text: '生命周期', link: '/advance/React/React_basics/03生命周期' },
            { text: '使用脚手架', link: '/advance/React/React_basics/04使用脚手架' },
            { text: '待办事项', link: '/advance/React/React_basics/05待办事项' },
            { text: 'ajax实战', link: '/advance/React/React_basics/06ajax实战' },
            { text: 'router5', link: '/advance/React/React_basics/07router5' },
            { text: 'router6', link: '/advance/React/React_basics/08router6' },
            { text: 'redux', link: '/advance/React/React_basics/09redux' },
          ],
        },
        {
          text: '进阶知识',
          collapsed: false,
          items: [{ text: '深入理解JSX', link: '/advance/React/React_advance/01深入理解JSX' }],
        },
        {
          text: 'Hooks',
          collapsed: false,
          items: [{ text: '动机', link: '/advance/React/React_Hooks/01动机' }],
        },
        {
          text: '实现原理',
          link: '/advance/React/React_src',
          collapsed: false,
          items: [{ text: '设计理念', link: '/advance/React/React_src/01设计理念' }],
        },
      ],
    },
  ],
  '/engineering/': [
    {
      text: '标准化',
      collapsed: false,
      items: [
        {
          text: 'Git',
          collapsed: false,
          items: [
            { text: '基本使用', link: '/engineering/standardization/Git/01基本使用' },
            { text: '配置公钥', link: '/engineering/standardization/Git/02配置公钥' },
            { text: '配置 husky', link: '/engineering/standardization/Git/03配置husky' },
          ],
        },
      ],
    },
    {
      text: '模块化',
      link: '/engineering/modularization/',
      collapsed: false,
      items: [
        {
          text: '模块化规范',
          link: '/engineering/modularization/specification/',
          collapsed: false,
          items: [
            { text: 'CommonJS', link: '/engineering/modularization/specification/01CommonJS' },
            { text: 'ESM', link: '/engineering/modularization/specification/02ESM' },
          ],
        },
        {
          text: 'Babel',
          collapsed: false,
          items: [{ text: '概述', link: '/engineering/modularization/babel/01概述' }],
        },
        {
          text: 'Webpack',
          link: '/engineering/modularization/webpack/',
          collapsed: false,
          items: [
            { text: '快速上手', link: '/engineering/modularization/webapck/01快速上手' },
            { text: '初体验', link: '/engineering/modularization/webapck/02初体验' },
            { text: '开发环境', link: '/engineering/modularization/webapck/03开发环境' },
            { text: '生产环境', link: '/engineering/modularization/webapck/04生产环境' },
            {
              text: 'Webpack 性能优化',
              link: '/engineering/modularization/webapck/05Webpack性能优化',
            },
            { text: 'Webpack5', link: '/engineering/modularization/webapck/06Webpack5' },
            { text: '笔记', link: '/engineering/modularization/webapck/07笔记' },
          ],
        },
        {
          text: 'Vite',
          collapsed: false,
          items: [{ text: '概述', link: '/engineering/modularization/Vite/01概述' }],
        },
        {
          text: 'Rollup',
          collapsed: false,
          items: [{ text: '概述', link: '/engineering/modularization/Rollup/01概述' }],
        },
      ],
    },
    {
      text: '自动化',
      collapsed: false,
      items: [
        {
          text: 'Node',
          collapsed: false,
          items: [
            { text: '基础', link: '/engineering/automation/Node/01基础' },
            { text: '异步编程', link: '/engineering/automation/Node/02异步编程' },
            { text: 'web 应用', link: '/engineering/automation/Node/03web应用' },
            { text: '模块机制', link: '/engineering/automation/Node/04模块机制' },
            { text: '发布 npm 代码', link: '/engineering/automation/Node/05发布npm代码' },
          ],
        },
        {
          text: '脚手架',
          collapsed: false,
          items: [
            { text: '约定路由脚手架', link: '/engineering/automation/cli/01约定路由脚手架' },
            { text: 'koa 脚手架', link: '/engineering/automation/cli/02koa脚手架' },
          ],
        },
        {
          text: '数据库',
          collapsed: false,
          items: [{ text: 'MongoDB', link: '/engineering/automation/database/01MongoDB' }],
        },
      ],
    },
  ],
  '/code/algorithm/': [
    {
      text: '算法与数据结构',
      collapsed: false,
      items: [
        { text: '数据结构', link: '/code/algorithm/basics/01数据结构' },
        { text: '排序算法', link: '/code/algorithm/basics/02排序算法' },
        { text: '快速幂', link: '/code/algorithm/basics/03快速幂' },
      ],
    },
  ],
  '/code/design_patterns/': [
    {
      text: '设计模式',
      collapsed: false,
      items: [
        { text: '概述', link: '/code/algorithm/design_patterns/01概述' },
        { text: '单例模式', link: '/code/algorithm/design_patterns/02单例模式' },
        { text: '策略模式', link: '/code/algorithm/design_patterns/03策略模式' },
        { text: '代理模式', link: '/code/algorithm/design_patterns/04代理模式' },
      ],
    },
  ],
  '/code/functional_programming/': [
    {
      text: '函数式编程',
      collapsed: false,
      items: [
        { text: '概述', link: '/code/algorithm/functional_programming/01概述' },
        { text: '纯函数', link: '/code/algorithm/functional_programming/02纯函数' },
        { text: '柯里化', link: '/code/algorithm/functional_programming/03柯里化' },
        { text: '函数组合', link: '/code/algorithm/functional_programming/04函数组合' },
        { text: '函子', link: '/code/algorithm/functional_programming/05函子' },
      ],
    },
  ],
  '/code/interview/': [
    {
      text: '面试必备',
      collapsed: false,
      items: [
        {
          text: '面试题',
          collapsed: false,
          items: [
            { text: '网络', link: '/code/interview/question/01网络' },
            { text: 'CSS', link: '/code/interview/question/02CSS' },
            { text: 'JavaScript', link: '/code/interview/question/03JavaScript' },
            { text: 'Vue', link: '/code/interview/question/04Vue' },
            { text: 'React', link: '/code/interview/question/05React' },
          ],
        },
        {
          text: '手写系列',
          collapsed: false,
          items: [
            { text: 'call', link: '/code/interview/hand_code/01函数call' },
            { text: '节流与防抖', link: '/code/interview/hand_code/02节流与防抖' },
            { text: '基本数组方法', link: '/code/interview/hand_code/03基本数组方法' },
            { text: '函数高级', link: '/code/interview/hand_code/04函数高级' },
            { text: '对象相关', link: '/code/interview/hand_code/05对象相关' },
            { text: '事件', link: '/code/interview/hand_code/06事件' },
          ],
        },
        {
          text: 'offer系列',
          collapsed: false,
          items: [
            { text: '面试准备', link: '/code/interview/offer/1.前端面试准备' },
            { text: '面试软技能', link: '/code/interview/offer/2.程序员面试软技能' },
            { text: 'offer收割机之HTML篇', link: '/code/interview/offer/3.offer收割机之HTML篇' },
            { text: 'offer收割机之CSS篇', link: '/code/interview/offer/4.offer收割机之CSS篇' },
            { text: 'offer收割机之JavaScript篇', link: '/code/interview/offer/5.offer收割机之JavaScript篇' },
            { text: 'offer收割机之性能优化篇', link: '/code/interview/offer/6.offer收割机之性能优化篇' },
            { text: 'offer收割机之前端工程化篇', link: '/code/interview/offer/7.offer收割机之前端工程化篇' },
            { text: 'offer收割机之计算机网络篇', link: '/code/interview/offer/8.offer收割机之计算机网络篇' },
            { text: 'offer收割机之浏览器原理篇', link: '/code/interview/offer/9.offer收割机之浏览器原理篇' },
            { text: 'offer收割机之手写代码篇', link: '/code/interview/offer/10.offer收割机之手写代码篇' },
            { text: 'offer收割机之代码输出篇', link: '/code/interview/offer/11.offer收割机之代码输出篇' },
            { text: 'LeetCode面试常考题目', link: '/code/interview/offer/12.LeetCode面试常考题目' },
            { text: 'offer收割机之Vue篇', link: '/code/interview/offer/13.offer收割机之Vue篇' },
            { text: 'vue项目的性能优化', link: '/code/interview/offer/14.vue项目的性能优化' },
            { text: 'react常考面试题', link: '/code/interview/offer/15.react常考面试题' },
            { text: 'typescript常考面试题', link: '/code/interview/offer/16.typescript常考面试题' },
            { text: '小程序面试题', link: '/code/interview/offer/17.小程序面试题' },
            { text: 'webpack-原理', link: '/code/interview/offer/18.webpack-原理' },
            { text: 'nodejs深入理解', link: '/code/interview/offer/19.nodejs深入理解' },
            { text: 'offer面试题', link: '/code/interview/offer/20.offer面试题' },
          ],
        },
      ],
    },
  ],
}
